config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :gnomes, only: %i[index show] do
    resources :bookings, only: %i[new create edit update]
  end
  get 'my_bookings', to: 'pages#my_bookings'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :gnome
  belongs_to :user
  validates :start_date, :end_date, presence: true
end

app/models/gnome.rb
class Gnome < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :name, presence: true
  validates :power, presence: true
  validates :price, presence: true

  has_many :bookings, dependent: :destroy

  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_name_power_and_price,
    against: [ :name, :power, :price ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @gnome = Gnome.find(params[:gnome_id])
    @booking = Booking.new(booking_params)
    @booking.gnome = @gnome
    @booking.user = current_user

    if @booking.save
      redirect_to my_bookings_path
    else
      render "gnomes/show"
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/gnomes_controller.rb
class GnomesController < ApplicationController
  # before_action :find_gnome, only: %i[show]

  def show
      @gnome = Gnome.find(params[:id])
      @booking = Booking.new
      @markers =  [{
          lat: @gnome.latitude,
          lng: @gnome.longitude,
          image_url: helpers.asset_url('gnomey.png'),
          info_window: render_to_string(partial: "info_window", locals: { gnome: @gnome })
        }]
  end

  def index
    if params[:query].present?
      @gnomes = Gnome.search_by_name_power_and_price(params[:query])
    else
      @gnomes = Gnome.all
    end

    @markers = @gnomes.geocoded.map do |gnome|
      {
        lat: gnome.latitude,
        lng: gnome.longitude,
        image_url: helpers.asset_url('gnomey.png'),
        info_window: render_to_string(partial: "info_window", locals: { gnome: gnome })
      }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def my_bookings
    set_counter
    @bookings = Booking.where(user: current_user)
    respond_to do |format|
      format.html
      format.json { render json: { bookings: @restaurants } }
    end
  end

  def home
    @gnomes = Gnome.all.sample(3)
  end

  def set_counter
    @booking_count = current_user.bookings.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gnomes/_info_window.html.erb
<% if action_name == "index" %>
  <h4><%= gnome.name %></h4>
  <p><%= gnome.address %></p>
  <p> <%= gnome.power %> </p>
  <div>
    <%= link_to 'Book', gnome_path(gnome), class: 'btn btn-primary book-button' %>
  </div>
<% else %>
  <p class="window-pop-up"><%= gnome.name%></p>
<% end %>

app/views/gnomes/index.html.erb
<div class="banner-index d-flex align-items-center justify-content-center mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path('gnomes_house.jpg')%>">
  <h1>Our magical Gnomes</h1>
</div>

<div class="container">
  <%= link_to root_path do %>
    <i class="fas fa-arrow-circle-left mb-5", id="music-btn"></i>
  <% end %>
  <div class="cards">
    <% if @gnomes.present? %>
      <% @gnomes.each do |gnome| %>
        <%= link_to gnome_path(gnome), class: "text-decoration-none" do %>
          <div class="card-gnome p-0">
            <div class="card-img" style="background-image: url('<%= cl_image_path gnome.photo.key %>')">
            </div>
              <div class="card-gnome-info">
                 <h3 class="gnome-name"><%= gnome.name %></h3>
                 <p class="title">Power</p>
                 <p> <%= gnome.power %></p>
                 <p class="title">About</p>
                 <p> <%= gnome.description %> </p>
                 <p class="price w-25"> €<%= gnome.price %> </p>
              </div>
            </div>
          <% end %>
        <% end %>
    </div>
    <div id="map"
         style="width: 100%; height: 600px;"
         data-markers="<%= @markers.to_json %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
    <% end %>
</div>



<script>
  function loadImage() {
  let audio_file = new Audio('https://www.soundjay.com/misc/magic-chime-01.mp3')
  audio_file.play();
  }
  loadImage()
</script>

app/views/gnomes/show.html.erb
<div class="gnome-container col-sm-6 col-lg-12">
  <%= link_to root_path do %>
    <i class="fas fa-arrow-circle-left mb-5", id="music-btn"></i>
  <% end %>
  <div class="card-gnome d-flex justify-content-between">
    <div class="card-gnome-infos">
      <%= cl_image_tag @gnome.photo.key, height: 400, width: 400, crop: :fill %>
    </div>
      <div class="calendar">
        <h1> <%= @gnome.name %></h1>
        <h5> <%= @gnome.power %></h5>
        <p> <%= @gnome.description %> </p>
        <h2 class="card-gnome-pricing"><%= @gnome.price %> €</h2>
          <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
            <h2>Your Reservation Date</h2>
            <%= simple_form_for [@gnome, @booking] do |f| %>
              <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
              <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
              <div class="form-buttons">
                <%= f.button :submit, "Book Gnome", class: "btn btn-primary" %>
              </div>
            <% end %>
        </div>
      </div>
        <div class="calendar">
          <h1> <%= @gnome.name %></h1>
          <h5> <%= @gnome.power %></h5>
          <p> <%= @gnome.description %> </p>
          <h2 class="card-gnome-pricing"><%= @gnome.price %> €</h2>
            <div class="form-wrapper" style="width: 400px; margin: 0 auto;">
              <h2>Your Reservation Date</h2>
              <%= simple_form_for [@gnome, @booking] do |f| %>
                <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
                <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"} %>
                <div class="form-buttons">
                  <%= f.button :submit, "Book Gnome", class: "btn btn-primary" %>
                  <%= link_to "Back", gnomes_path %>
                </div>
              <% end %>
            </div>
        </div>
  </div>
  <div class="col-sm-4 col-lg-12" id="map" style="width: 100%; height: 600px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        <%= cl_image_tag @gnome.photo.key, height: 400, width: 400, crop: :fill%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gnomify</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body class='module-toad'>
    <div class="page-container">
      <%= render "shared/navbar" %>
      <%= render "shared/search-form" %>
      <%= render "shared/flashes" %>
    <main id="main-content">
      <%= yield %>
    </main>
    <%= render "shared/footer" %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path('forest.jpg')%>">
  <div class="main-container col-sm-6 col-lg-12">
    <h1>Behold the Gnomes</h1>
    <div class="btn btn-light">
      <%= link_to "Discover", gnomes_path %>
    </div>
  </div>
</div>

<div class="container">
  <div class="title-paragraph-homepage">
    <h3 class="title-homepage mb-3">Feeling lonely while gardening?</h3>
    <p class="paragraph">We have the right solution for you. Rent our magical Gnomes until you run their powers out!</p>
    </div>
  <div class="card-container">
    <div class="row">
      <% @gnomes.each do |gnome| %>
      <div class="d-flex justify-content-between col-sm-6 col-md-4 class_style">
      <%= link_to gnome_path(gnome) do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path gnome.photo.key, height: 300, crop: :fill %>')">
        <p><%= gnome.name %></p>
      </div>
      <% end %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/pages/my_bookings.html.erb
<div class="banner-index d-flex align-items-center justify-content-center mb-5" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path('mushrooms.jpg')%>">
  <h1>My bookings</h1>
</div>
<div class="flex-center mt-4" data-controller="counter">
  <div class="counter">
    <span data-counter-target="count"><%= @booking_count %></span>
  </div>
</div>

<div class="container">
  <%= link_to root_path do %>
    <i class="fas fa-arrow-circle-left mb-5", id="music-btn"></i>
  <% end %>
    <% @bookings.each do |booking| %>
    <div class="card-horizontal">
      <%= cl_image_tag booking.gnome.photo.key, height: 250, width: 240, crop: :fill, radius: 8 %>
      <div class="card-horizontal-info">
        <h3 class="gnome-name-title"><%= booking.gnome.name %></h3>
        <p class="title">Power</p>
        <p><%= booking.gnome.power %></p>
        <p class="title">Start Date</p>
        <p><%= booking.start_date %></p>
        <p class="title">End Date</p>
        <p class="end-date"><%= booking.end_date %></p>
      </div>
      <div class="status">
        <p>Complete</p>
      </div>
    </div>
    <% end %>
  </div>
  <figure class="rainbow smooth mb-3"></figure>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>

  </div>
  <div class="footer-copyright">
    Gnomes <i class="fas fa-heart"></i> by Louise, Luís, Mariana and Patrícia
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "clover_024.jpg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "user.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Bookings", my_bookings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search-form.html.erb
<div class="py-3 d-flex justify-content-center">
  <div class="col-8">
  <div class="col-12">
      <%= form_tag gnomes_path, method: :get, class: 'form-inline flex-grow-1' do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control flex-grow-1",
          placeholder: "Find a gnome"%><%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
  </div>
  </div>
</div>